### ISSUE TITLE
responsive mobile et dolidroid

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/DoliSMQ#1485]

**Comment by Eoxia-maxime** [comment]
![image](https://github.com/Evarisk/DoliSMQ/assets/108923590/7ea1ba96-5c0a-413f-8929-325017beaf3e)

**Comment by Eoxia-maxime** [comment]
![image](https://github.com/Evarisk/DoliSMQ/assets/108923590/61f9005c-de35-4a6e-b091-056bd92c9444)
