### ISSUE TITLE
Incohérence interface publique manque des données

### ISSUE THREAD

**Issue by lmag** [Evarisk/DoliSMQ#1509]
![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/443954af-a548-461e-bea7-308b5bec9227)
VS
![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/00c94ae9-9e4b-45f9-a883-df1d3b8ef864)

Ajout données sur le listing publique
![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/b5d9d9f0-7163-4523-9c81-9f0fa9c54ea8)

**Comment by nicolas-eoxia** [comment]
fix by #1487
