### ISSUE TITLE
Interface publique manque le message d'information

### ISSUE THREAD

**Issue by lmag** [Evarisk/DoliSMQ#1510]
![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/18a93b2f-50ae-44f2-a36c-56b34487251c)

**Comment by nicolas-eoxia** [comment]
Fix avec saturne (https://github.com/orgs/Evarisk/projects/54?pane=issue&itemId=36825326)

**Comment by nicolas-eoxia** [comment]
- [ ]
