### ISSUE TITLE
Configuration des objets pour un modèle de contrôle

### ISSUE THREAD

**Issue by eoxia-amandine** [Evarisk/dolismq#218]

**Comment by eoxia-amandine** [comment]
![process-modification-controle](https://user-images.githubusercontent.com/18576747/155750889-4d1cd67a-8fe6-4c44-89f5-0f5fc92bc76e.png)

**Comment by lmag** [comment]
Done
![image](https://user-images.githubusercontent.com/3288514/200279919-70d2f25b-c692-4c70-9b72-4040519a90c3.png)
