### ISSUE TITLE
[IHM] - Modéliser le WorkFlow avec le suivi des actions dans le temps

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolismq#255]

**Comment by lmag** [comment]
Rendu final:
![image](https://user-images.githubusercontent.com/3288514/164726684-e95dd52a-8476-49ef-8431-f6af092197b6.png)
Partie Question
![image](https://user-images.githubusercontent.com/3288514/164726859-f1043500-7424-4f6c-af9b-1d446ada31d3.png)
avec seuil de réussite

**Comment by lmag** [comment]
Il faut comparer avec DoliSMQ et modéliser le WorkFlow @eoxia-amandine

**Comment by lmag** [comment]
Il manque : 
- Historique (on l'a dans DoliSMQ)
- Les familles ou TAG
- Le % de complétude
- Le choix du nom des réponses ou questions
- Tableau de bord qui pourrait être construit par famille et rapport de contrôle

**Comment by lmag** [comment]
![image](https://user-images.githubusercontent.com/3288514/169537227-b7ff0dfd-e337-4705-b7dc-ecf4c767c029.png)

**Comment by lmag** [comment]
List des TAG : 

- Bureau Etude
- Qualité
- Hygiène Sécurité
- Environnement
- Fournisseurs
- Réglementaire
- Commercial
- Production
- Méthodes

**Comment by lmag** [comment]
@MartinHennes

**Comment by MartinHennes** [comment]
https://xd.adobe.com/view/fda2214e-8400-45e3-9c49-a073c6637142-a8f1/

Visuel Réglementaire comme vu hier
