### ISSUE TITLE
Action bouton enregrister/validation

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/dolismq#271]
par défaut enregistrer gris et validation violet 
si une modification est détecter alors enregristrer passe a violet et valider gris

**Comment by lmag** [comment]
Etat 1 : Par défaut = tout est enregistré
Enregistrer = Gris et Valider = Violet
Etat 2 : Manque des données non enregistrés
Enregistrer = Violet et Valider = Gris
