### ISSUE TITLE
Pouvoir rendre obligatoire les réponses sur certains formulaire

### ISSUE THREAD

**Issue by lmag** [Evarisk/DoliSMQ#289]
Etudier les obligations des questions :
Question
Formulaire
Sur les objets

- [x] getpost('mandatory') a revoir
- [x] nommer les post bien, c'est des id ca doit apparaitre dans le nom
- [x] strlen sur object->mandatory dans set_mandatory
- [x] seteventmessage avant headers
- [x] en sql : NOT NULL DEFAULT ''
- [x] pas besoin de check != 'null'
- [x] pas besoin du input hidden sheet id
- [x] enlever unmandatory
- [x] envoyer en input hidden item id en tant que questionId

04d2dabd217f03f28ebe4fde4e6839f88d4d64ee

L270 / GetPost check type
L272 > 0
L273 dol_strlen
L286 check getpost inutile
L287 seteventmessage plutot
L785 heck avec le SQL -> check inutile surement
L786 Ligne inutile

SetEventmessage mettre la ref question
centrer la checkbox et le titre obligatoire
L712 virer id
L709 le mettre dans l'action du form
L713 pas besoin de "" sur le checked + un espace

**Comment by lmag** [comment]
![image](https://user-images.githubusercontent.com/3288514/206196714-5cc71be8-193d-42d8-8452-d072f6cfff96.png)

**Comment by evarisk-micka** [comment]
Faire en sorte que les questions soient mise obligatoire sur la fiche de modèle
