### ISSUE TITLE
[DATAMODEL] - Pouvoir configurer les types de réponses à une question

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/DoliSMQ#318]
Aujourd'hui, on peut répondre à une question par OK, KO, Non concerné, A réparer

Il faut pouvoir configurer à la création d'une question les réponses possibles 
ces réponses sont stockées dans dolismq_answers et les liens entre la question et les réponses sont stockées dans element_element

types de réponses :
(choix multiple) OK, KO, Non concerné, A réparer
Entier (nb de kilomètres)
Vrai/faux
Poucentage
Champ texte

https://app.diagrams.net/#G1WI7K_W7R4cdTu0K4ITTnBLjooFc33A_l

**Comment by lmag** [comment]
Type de question pour DoliSMQ 1 Type
4 questions
OK - 100%
KO - 0%
Encours = à réparer = 1 à 99% + affichage du %
NA - Pas de %
Photo 1 - Visible ou pas
Photo 2 - Visible ou pas

Visibilité des questions
0;N'est pas affiché
1;est affiché

Actions
Attention une question non affichée ne compte pas dans le scoring

Scoring en % pour les questions
0;Ne compte pas dans le résultat
1;Compte dans le résultat

**Comment by lmag** [comment]
![image](https://user-images.githubusercontent.com/3288514/169564549-b6315e9f-302e-45ae-bec6-db660476ff94.png)

**Comment by evarisk-theo** [comment]
![image](https://user-images.githubusercontent.com/68421590/229176406-b4c589e7-a7f5-40d5-94c2-aecece1630ea.png)

**Comment by evarisk-theo** [comment]
types de réponses possibles : 
- sélecteur entre plusieurs possibilités
- range

si questiondet : on ne peut pas réutiliser une réponse pour d'autres questions
si answer : on peut, et on peut configurer les éventuelles images de la réponse, mais ça ajoute une étape au workflow (créer réponse puis créer question puis fiche modele puis controle)

solutino retenue => questiondet
