### ISSUE TITLE
[IHM] - Maquette pour les contrôles réalisés a partir d'un téléphone mobile

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/dolismq#336]
9e811cc117d10f4d63672e750a2b5cc97b276da9
50defcbb9a852de48e815319d8fc7e7ad6b90c53

**Comment by MartinHennes** [comment]
https://xd.adobe.com/view/7be43c1a-71e7-4dd9-8e17-bbd06c7e3670-2eb7/

**Comment by MartinHennes** [comment]
https://xd.adobe.com/view/bb82d473-6309-4d76-9e6e-900d55d2ed99-eed1/

Cocher dans le premier écran le type d'affichage souhaité puis cliquer sur créer
Possibilité ajout photos depuis appareil et/ou galerie
Cliquer sur les boutons OK/KO

Possibilité de retourner au formulaire en cliquant en bas pour changer l'affichage

**Comment by MartinHennes** [comment]
Lignes en bord à bord

style dolibarr

photos derrière l'appareil quand ajoutées

Bouton pour tout cocher/décocher 

Pas d'espace entre les questions 

Economiser espace à fond 

Grader système de croix pas croix  

Bandeau en haut lacunaire

**Comment by MartinHennes** [comment]
https://xd.adobe.com/view/690a9418-6a6c-48e0-9bf9-28770f9d1917-3c59/

**Comment by MartinHennes** [comment]
Maquette contrôle téléphone adapté bootstrap
![Maquette_classes_bootstrap](https://user-images.githubusercontent.com/105202836/172857387-ac5ac237-d1cc-419c-89de-c38b6f80dd20.png)

**Comment by lmag** [comment]
Bravo Martin Hennes UX-Designer :)

**Comment by Alexandra-copac** [comment]
Bravo c'est top! Moi je valide!

**Comment by MartinHennes** [comment]
Représentation plus claire de l'adaptation Bootstrap avec classes copiables/collables

[IHM Control Card Mobile Bootstrap.pdf](https://github.com/Evarisk/dolismq/files/8910542/IHM.Control.Card.Mobile.Bootstrap.pdf)

**Comment by nicolas-eoxia** [comment]
Intégration fonctionnelle de la maquette 
![image](https://user-images.githubusercontent.com/52404047/205670126-e6280fcc-8407-4739-8691-bf68e9cf4e48.png)

Toggle en php et JS
