### ISSUE TITLE
filtrer sur un élément vide

### ISSUE THREAD

**Issue by lmag** [Evarisk/DoliSMQ#459]
9c822ebe3bea5303d0541482bd3cb224f05cfeec
b1f02540629cab10bfd10ac5e2ee291a53c7fe95

N/A -> pas de verdict

Pouvoir filtrer le verdict avec :

- [x] Pas de verdict
- [x] Verdict OK
- [x] Verdict KO
- [x] Tout (verdict/pas verdict)

![image](https://user-images.githubusercontent.com/3288514/176397760-2eb69577-c065-4f7b-9ee6-e83a4bce7edd.png)

**Comment by nicolas-eoxia** [comment]
le show empty affiche tout
