### ISSUE TITLE
BUG - Ecran blanc au moment de la validation du fastupload

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolismq#487]
Lorsque l'on tourne la tablette dans les 2 sens l'écran apparait
@titicopac prendre les copies d'écrans

**Comment by titicopac** [comment]
J'ai réalisé 5 contrôles en plus pour essayer de récupérer les URL ou il y avait le problème.
Le bug ne s'est pas représenté.
A voir avec le temps lors des futurs contrôle si le bug revient ou si s'est c'était juste un problème éphémère.
