### ISSUE TITLE
COP - Ajouter les TAG sur les controles

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolismq#494]
2398385c070acbd1a2f99e8656324eaf447e5bcf
037178fb57de502cef4dac1c9fab5b9a60719094

![image](https://user-images.githubusercontent.com/3288514/196996819-983f6fe0-72f3-439d-88ee-805bd749bb76.png)

**Comment by nicolas-eoxia** [comment]
+ rendre obligatoire le tags si dans le modèle coché

**Comment by lmag** [comment]
Des tags différents sur tous les objets

- [ ] Questions
- [ ] Fiches modèles
- [ ] Contrôles
