### ISSUE TITLE
améliorer séparation champs objet / objets liés dans control_card

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/DoliSMQ#506]
a7f56fde299c786b855a18c6ba43168460205e60

![image](https://user-images.githubusercontent.com/52404047/204023015-f6f13ff0-2a7a-4b8c-94ac-3680d606ac90.png)

**Comment by eoxia-amandine** [comment]
A reprendre le HTML de la page "Créer contacts/adresses"
![image](https://user-images.githubusercontent.com/18576747/205858960-db388294-5860-4b20-bf55-13ddcdb2a79e.png)
