### ISSUE TITLE
[IHM] - Création des copies d'écrans

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolismq#7]
Création des copies d'écrans

**Comment by eoxia-amandine** [comment]
**Réglages**
![1-reglages](https://user-images.githubusercontent.com/18576747/146944295-08673b37-d3c8-4dcf-9df0-89ceb1eeb45e.png)

**Ajout question**
![2-ajout-question](https://user-images.githubusercontent.com/18576747/146944335-c9b0f0e3-ecd3-4677-ae89-af221a647c11.png)

**Ajout modèle**
![3-ajout-modele](https://user-images.githubusercontent.com/18576747/146944362-1cac6c37-7145-42b9-8e8d-5814ec47473d.png)

**Fiche de contrôle**
![4-fiche-de-controle](https://user-images.githubusercontent.com/18576747/146944384-96a698b0-7510-4597-a778-875cc6b349bb.png)

**Comment by eoxia-amandine** [comment]
V2
Lien du prototype : https://xd.adobe.com/view/7aab582f-e8f7-48b0-9e05-ca1cddeff12b-2ff8/?fullscreen

Maquettes JPEG :
![liste-questions](https://user-images.githubusercontent.com/18576747/147066879-e5614eb6-2bce-4565-8477-884852a74f10.png)
![ajout-question](https://user-images.githubusercontent.com/18576747/147066889-61712d1f-ac4b-4fdf-921e-de7d0e9ec0a3.png)
![liste-modeles](https://user-images.githubusercontent.com/18576747/147066901-d3f7c79d-12de-4a01-b332-f1ae803ba9b3.png)
![ajout-modele](https://user-images.githubusercontent.com/18576747/147066910-77bf246a-b44a-459f-9c3e-a7cf89966dc1.png)
![ajout-modele-2](https://user-images.githubusercontent.com/18576747/147066915-44e94f93-e87d-4967-bde8-a8360cd412fe.png)
![listing-controles](https://user-images.githubusercontent.com/18576747/147066921-eef88286-3c83-4d76-b853-37662a9257ed.png)
![ajout-controle](https://user-images.githubusercontent.com/18576747/147066930-ce0577f2-96b9-4aad-b606-2d82336e9d73.png)
![ajout-contrôle2](https://user-images.githubusercontent.com/18576747/147066938-98782940-6de7-4153-8d5b-41ae85d07b2f.png)

**Comment by eoxia-amandine** [comment]
Retours suite à la réunion :

**Modifier** ordre de l'ajout des contrôles (3.2)

1. Choix du produit
2. Choix du lot/n° série
3. Choix du modèle de contrôle

On enlève le champ "Contrôleur" car il est définit en automatique et ne **peut pas être modifié**
